# Generated by Django 3.2.5 on 2021-12-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('IdReceitas', models.AutoField(primary_key=True, serialize=False)),
                ('Receitas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdUsuarios', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Senha', models.CharField(max_length=20)),
                ('Estado', models.CharField(max_length=80)),
                ('Data_de_Nascimento', models.DateField()),
                ('Telefone', models.CharField(max_length=20)),
                ('Estado_Civil', models.CharField(choices=[('Solteiro', 'S'), ('Casado', 'C'), ('Divorciado', 'D')], max_length=10)),
                ('Chef_e_ou_Cliente', models.CharField(choices=[('Sim - Sim', 'S - S'), ('Sim - Não', 'S - N'), ('Não - Sim', 'N - S')], max_length=9)),
                ('Itens_Comprados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('IdReceitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Acessos_IdReceitas', to='Me_Ajuda_Chefe.receitas')),
                ('IdUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Acessos_IdUsuarios', to='Me_Ajuda_Chefe.usuario')),
            ],
        ),
    ]
